{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c28864eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-04-09 20:14:14.398 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Anaconda 3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from openai import AzureOpenAI\n",
    "from azure.core.credentials import AzureKeyCredential\n",
    "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
    "import numpy as np\n",
    "import faiss\n",
    "from langchain_community.document_loaders import TextLoader\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_core.vectorstores import VectorStoreRetriever\n",
    "from langchain.chains import RetrievalQA\n",
    "from langchain_openai import OpenAIEmbeddings\n",
    "from langchain.llms import AzureOpenAI\n",
    "from langchain_openai import AzureOpenAIEmbeddings\n",
    "from langchain.prompts import PromptTemplate\n",
    "from langchain.chains.question_answering import load_qa_chain\n",
    "from langchain_core.messages import HumanMessage\n",
    "from langchain_openai import AzureChatOpenAI\n",
    "import openai\n",
    "import streamlit as st\n",
    "\n",
    "\n",
    "# Setup environment variables for API keys and endpoint\n",
    "os.environ[\"OPENAI_API_KEY\"] = \"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\"\n",
    "os.environ[\"AZURE_OPENAI_API_KEY\"] = \"251bab4a00c6407c9edb695c5f450a5d\"\n",
    "os.environ[\"AZURE_OPENAI_ENDPOINT\"] = \"https://surface-llm-poc.openai.azure.com/\"\n",
    "\n",
    "# Function to read text from file\n",
    "def get_text_from_file(txt_file):\n",
    "    with open(txt_file, 'r',encoding='latin') as file:\n",
    "        text = file.read()\n",
    "    return text\n",
    "\n",
    "# Function to split text into chunks\n",
    "def get_text_chunks(text):\n",
    "    text_splitter = RecursiveCharacterTextSplitter(chunk_size=10000, chunk_overlap=1000)\n",
    "    chunks = text_splitter.split_text(text)\n",
    "    return chunks\n",
    "\n",
    "# Function to create and store embeddings\n",
    "def get_vector_store(text_chunks):\n",
    "    embeddings = AzureOpenAIEmbeddings(azure_deployment=\"Large_Embeddings\")\n",
    "    vector_store = FAISS.from_texts(text_chunks, embedding=embeddings)\n",
    "    vector_store.save_local(\"faiss_index\")\n",
    "    return vector_store\n",
    "\n",
    "# Function to setup the vector store (to be run once or upon text update)\n",
    "def setup(txt_file_path):\n",
    "    raw_text = get_text_from_file(txt_file_path)\n",
    "    text_chunks = get_text_chunks(raw_text)\n",
    "    get_vector_store(text_chunks)\n",
    "    print(\"Setup completed. Vector store is ready for queries.\")\n",
    "\n",
    "# Function to get conversational chain\n",
    "def get_conversational_chain():\n",
    "    prompt_template = \"\"\"\n",
    "    Answer the question as detailed as possible from the provided context,if question asked about future based on the provided data give answers by prediction, make sure to provide all the details, if the answer is not in\n",
    "    provided context just say,\"answer is not available in the context\", don't provide the wrong answer\\n\\n\n",
    "    Context:\\n {context}?\\n\n",
    "    Question: \\n{question}\\n\n",
    "\n",
    "    Answer:\n",
    "    \"\"\"\n",
    "    model = AzureChatOpenAI(\n",
    "    azure_deployment=\"SurfaceLLM\",\n",
    "    api_version='2023-12-01-preview')\n",
    "    prompt = PromptTemplate(template=prompt_template, input_variables=[\"context\", \"question\"])\n",
    "    chain = load_qa_chain(model, chain_type=\"stuff\", prompt=prompt)\n",
    "    return chain\n",
    "\n",
    "# Function to handle user queries using the existing vector store\n",
    "def query(user_question, vector_store_path=\"faiss_index\"):\n",
    "    embeddings = AzureOpenAIEmbeddings(azure_deployment=\"Large_Embeddings\")\n",
    "    vector_store = FAISS.load_local(vector_store_path, embeddings, allow_dangerous_deserialization=True)\n",
    "    chain = get_conversational_chain()\n",
    "    docs = vector_store.similarity_search(user_question)\n",
    "    response = chain({\"input_documents\": docs, \"question\": user_question}, return_only_outputs=True)\n",
    "    return response[\"output_text\"]\n",
    "\n",
    "def main():\n",
    "    st.title(\"Consumer Reviews Synthesis!\")\n",
    " \n",
    "    # Predefined text file path\n",
    "    txt_file_path = \"All_Reviews.txt\"\n",
    " \n",
    "    # Automatically call setup with the predefined file on startup\n",
    "    if not os.path.exists(\"faiss_index\"):\n",
    "        setup(txt_file_path)\n",
    " \n",
    "    # User input for query\n",
    "    user_question = st.text_input(\"Ask your question\")\n",
    " \n",
    "    if st.button(\"Submit\"):\n",
    "        if os.path.exists(\"faiss_index\"):\n",
    "            response = query(user_question)\n",
    "            st.write(\"Response:\", response)\n",
    "        else:\n",
    "            st.error(\"The vector store setup has failed. Please check the file path and try again.\")\n",
    " \n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "aab9af5e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# embeddings = AzureOpenAIEmbeddings(azure_deployment=\"Large_Embeddings\")\n",
    "# vector_store = FAISS.from_texts(text_chunks, embedding=embeddings)\n",
    "# vector_store.save_local(\"faiss_index\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "3a449a6b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# def get_text_from_file(txt_file):\n",
    "#     with open(txt_file, 'r',encoding='latin') as file:\n",
    "#         text = file.read()\n",
    "#     return text\n",
    "\n",
    "# # Function to split text into chunks\n",
    "# def get_text_chunks(text):\n",
    "#     text_splitter = RecursiveCharacterTextSplitter(chunk_size=10000, chunk_overlap=1000)\n",
    "#     chunks = text_splitter.split_text(text)\n",
    "#     return chunks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "198545e5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# txt_file_path = \"cp_reviews.txt\"\n",
    "# raw_text = get_text_from_file(txt_file_path)\n",
    "# text_chunks = get_text_chunks(raw_text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7274a8cc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
